### ISSUE TITLE
Incorrectly recognizes the codename of enchilada

### ISSUE THREAD

**Issue by Louis2747** [amo13/Anarchy-Droid#10]
The codename of the OnePlus 6 is "enchilada". Anarchy-Droid incorrectly recognizes this as "oneplus6", I think this might be because the model number of my device gets recognized as "ONEPLUS A6003", while in codenames.yml it is listed as "a6003", Although I don't know anything about how this works other than what I read in the "I want to help" section.
![image](https://user-images.githubusercontent.com/52701949/148606278-d43dc0c9-8cbd-4a22-a96d-e67ae5ebe6f3.png)

**Comment by amo13** [comment]
Thanks for reporting! I added "oneplus a6003" to `codenames.yml`. This should fix the wrong codename recognition.

**Comment by amo13** [comment]
You need to restart the application for the new fix to be taken into account.

**Comment by Louis2747** [comment]
Sorry I almost forgot, yes it does work now. And thank you for the really fast answer!
