### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by n0toose** [amo13/Anarchy-Droid#16]
I'd like to contribute a couple of patches to this project. Is it possible for you to add some sort of software license, so that the legality of me using your code and you using the code of contributors isn't questionable? Many thanks!

**Comment by amo13** [comment]
There is a license file in the repo. It set it up directly with github when initiating the repo.
It's GPL3.
Your contributions are very welcome. 
If you have any question about the code, ask right away.

**Comment by n0toose** [comment]
Oh, silly me, I missed the `LICENSE` file because I was looking for a `COPYRIGHT` file. My bad, apologies!
