### ISSUE TITLE
trying to recognizethe device...

### ISSUE THREAD

**Issue by jithinjames916** [amo13/Anarchy-Droid#17]
i am using linux(arch)... i downloaded exicutable file, factory reset the phone and did as said; in phone(develper option and all) and connect my phone(redmi 4A) but its stuck in this screen, if you know what went wrong please reply...

**Comment by amo13** [comment]
Do you have TWRP already installed and running when connecting it? If so, please provide some logs (from the log folder). If not, then you shouldn't be able to start any procedure because redmi is not supported as a brand for TWRP installation.
