### ISSUE TITLE
Add information about the source and build date of roms

### ISSUE THREAD

**Issue by rradar** [amo13/Anarchy-Droid#21]
Hello again,

I would find it very useful if some information about the sources could be present together with the "date" of the rom.

It looks like that roms from the archive are hand picked - right? Would be great to get a indication how old (or up to date) the roms are.

Also how could be more roms/devices be added? By opening a issues here?

Greetings

**Comment by amo13** [comment]
Thanks for your suggestions.
Yes, the roms from the archive are hand picked for a few more or less random devices with no official rom releases. A lot of them are older devices. 
I actually don't have more information on the roms in the archive than what their file names already provide. A lot of them should have a date in their file name, but some very old roms for very old devices don't. 

As for adding roms and devices, it depends on what you have in mind.
* For adding a rom zip file to the archive, dropping a link in here with a few words (which device, rom stability, maybe experience with it) would be enough.
* For adding a rom source systematically to Anarchy-Droid, like adding MoKee or the like as selectable rom in the application if available for the given device, we would need to write a a few scraper functions. One of the go files for another rom could easily be taken as a starting point, like [DivestOS](https://github.com/amo13/Anarchy-Droid/blob/master/get/divestos.go) if there is an API or [CarbonRom](https://github.com/amo13/Anarchy-Droid/blob/master/get/carbonrom.go) if directly scraping the website. Note here, that scraping websites which use client-side javascript to build the site, like [MoKee](https://download.mokeedev.com) unfortunately, scraping becomes very (too) difficult. In that case, we would need to contact the developer or rom team and ask for some OTA API or something like that.
* For adding a whole new brand of devices, the main concern is unlocking the bootloader and the communication with it. To see how it is done for currently supported brands, see [fastboot.go](https://github.com/amo13/Anarchy-Droid/blob/master/device/fastboot/fastboot.go). If you have any question about the code, I'd be glad to answer them.
* Finally, if a device of a brand that *should* be supported does not work with Anarchy-Droid, we need to investigate. If many cases, it is just some issue of correctly finding the codename and brand of the devices after if is connected. In most cases, this is as easy as adding an appropriate entry to the according [lookup file](https://github.com/amo13/Anarchy-Droid/tree/master/lookup) which takes precedence over using google's [bis CSV file](http://storage.googleapis.com/play_public/supported_devices.csv) for the lookups.
