### ISSUE TITLE
Add support for HTC One S (ville)

### ISSUE THREAD

**Issue by rradar** [amo13/Anarchy-Droid#27]
> As for adding roms and devices, it depends on what you have in mind.
>
 >   For adding a rom zip file to the archive, dropping a link in here with a few words (which device, rom stability, maybe experience with it) would be enough.

Device: HTC One S
Codename: ville

Most recent stable rom I'm aware of is located here: [lineage-14.1-20200523-UNOFFICIAL-ville.zip](https://www.androidfilehost.com/?fid=4349826312261817021) (author posted the link [here](https://forum.xda-developers.com/t/rom-7-1-unofficial-s4-hboot2-16-lineageos14-1-htc-one-s-ville-2018-08-20.3540981/page-19#post-82648239))

**Comment by amo13** [comment]
I added it to the archive, thank you for the links.
For Anarchy-Droid to work, one will still have to unlock the HTC device and install TWRP by oneself. The former seems to be anything but easy for HTC devices though.
