### ISSUE TITLE
The application constantly ask to update version 1.2.5

### ISSUE THREAD

**Issue by hamed-rezaee** [amo13/Anarchy-Droid#30]
I have already downloaded version 1.2.6, however, the app version is 1.2.5 and it constantly asks to update version 1.2.6 and won't allow running the application.

![image](https://user-images.githubusercontent.com/13097270/167263242-570d6b0e-8625-4b8b-8964-bc3a5df70f2a.png)

**Comment by amo13** [comment]
Oh damn... Let me fix that later today.
Thanks for reporting!

**Comment by amo13** [comment]
Should be fixed now. Please report back if it's not.
