### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jakbin** [amo13/Anarchy-Droid#39]
i am getting this error when try to run Anarchy-Droid_linux_amd64 in kali linnux .

Setup Anarchy-Droid 1.4.2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa60625]

goroutine 27 [running]:
github.com/amo13/anarchy-droid/logger.Report(0x0?)
        /home/runner/work/Anarchy-Droid/Anarchy-Droid/logger/logger.go:90 +0x9e5
created by main.main.func2
        /home/runner/work/Anarchy-Droid/Anarchy-Droid/main_unix.go:106 +0xaa

**Comment by amo13** [comment]
Thanks for reporting. Does Anarchy-Droid have access to the internet when you launch it?

**Comment by jakbin** [comment]
Yes

**Comment by jakbin** [comment]
> Thanks for reporting. Does Anarchy-Droid have access to the internet when you launch it?

Yes

**Comment by jakbin** [comment]
I fix it , first I download v1.4.1 and then I run it , and this version works . 

Then I run v1.4.2 . Then it works also .
